version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - custombridge-pvp
    volumes:
      - MongoVol-pvp:/data/db
  springapp:
    image: dockerpvp/springbootapp:1
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_HOSTNAME=mongodb
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=admin
    networks:
      - custombridge-pvp

volumes:
  MongoVol-pvp:
    driver: local

networks:
  custombridge-pvp:
    driver: bridge
